# Generated by CONDENSATOR 34XX !
x = 1
y = 2
z = 3
def main():
    new = "Ouiiii"
    return new
mydict = {"oui": "non","hello": False,"peut-etre": {"ui": 1}}
x = 0
def ui():
    pass
def F(string: str,nb: int):return {"ui": True    }
lst = [
    {"nom": "Theo"},
    {"nom": "Theo"},
{"nom": "Theo"    }
]
compr = [ i
    for i in range(len(lst)    )
]